### ISSUE TITLE
[tracker] Implement development workflow to support iris-core and reduce risk

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/iris#560]
**Development Workflow**
- [x] Add labels for issues: [bug][maintenance][enhancement][in progress][invalid][wontfix][duplicate]
- [x] slack bot for github
- [ ] Team alias for reviews

**Unit Tests**
- [ ] write a set of unit tests for iris api functionality #470 
- [ ] Run in travis on each PR
- [ ] Include coveralls for code coverage
- [ ] automated dependency management (dependabot) #532 

**Linting**
- [x] Implement code formatter such as black #558
- [x] Include flake8 linting in Travis (should block builds) #553

**Documentation**
- [x] condense wiki docs into a readme: provide concise and clear instructions for requirements, usage, and examples #558
- [ ] Create template with instructions for filing new bugs, add to readme 
- [ ] Contribution guidelines
- [x] Github badges: pypi version, travis build status, issues, license,  etc
